version: "3.9"

services:
    db:
        image: mariadb
        container_name: mariadb 
        restart: on-failure
        ports:
            - 3306:3306
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    adminer:
        image: adminer
        container_name: adminer
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8080:8080

    php:
        image: dekpo/my-custom-php
        container_name: php
        depends_on:
            - db
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./public:/var/www/html/
            - .:/var/www/
